### ISSUE TITLE
LevelView里面的代码全是错的，是MainActivity的代码。。。。。

### ISSUE THREAD

**Issue by lanhaogang** [canney-chen/android-projects#1]
如题，希望作者有空修改

**Comment by canney-chen** [comment]
> 如题，希望作者有空修改

是编译出错了吗？ 我看了代码没有问题，

**Comment by lanhaogang** [comment]
> > 如题，希望作者有空修改
> 
> 是编译出错了吗？ 我看了代码没有问题，

LevelView.java 和 MainActivity.java 这两个文件里的代码一模一样，肯定编不过哇
